site_name:'Maximizing Stakeholder Engagement in Open Environmental Data Science'
site_description: 'AGU 2023 Innovation Session'
site_author: Ty Tuff
site_url: https://cu-esiil.github.io/agu-2023_innovation_session

# Repository
repo_name: agu-2023_innovation_session
repo_url: https://github.com/CU-ESIIL/agu-2023_innovation_session
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Colorado Boulder'

# Page tree
nav:
  - Home: index.md
  # TODO: Add your nav sections / sub-sections and path to markdown page Ex:
  # - Remote Sensing:
  #     - How to Cloud Correct Sentinel-2 Images: remote_sensing/sentinel_2_cloud_correction/sentinel_2_cloud_correction.md

# Configuration
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  #logo: # TODO: Uncomment and add path to your logo .png Ex: 'assets/ESIIL_logo.png'
  #favicon: # TODO: Uncomment and add path to your favicon .png Ex: 'assets/favicon.ico'
  # setting features for the navigation tab
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Options
extra:
  social:
    - icon: fontawesome/brands/github
     # link: https://cu-esiil.github.io/AGU2023

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
